### ISSUE TITLE
Braces \{ and \} Not Rendering

### ISSUE THREAD

**Issue by austinmohr** [jamesdabbs/pi-base#38]
For example: http://pi-base.herokuapp.com/spaces/10

Oddly, the auto-preview shown while editing is correct, but the main display on the space page is lacking all braces. Probably this is issue is related to escaping.

**Comment by jamesdabbs** [comment]
Fixed in a5c94e6

This is definitely an escaping issue from a bad interaction with the MathJax, Markdown, and HTML escaping. I would not be at all surprised if there are other edge cases like this - please open a new issue if you run into anything else similar.
