### ISSUE TITLE
Image Hosting

### ISSUE THREAD

**Issue by austinmohr** [jamesdabbs/pi-base#41]
Related to (but separate from) the issue of "official" images is the problem of hosting images. We can always outsource this to a site like imgur, but I think it best if we can be as self-contained as possible.

**Comment by jamesdabbs** [comment]
I'm all for keeping things internal and Amazon S3 is _essentially_ free. Looks like there are some good tools that should make this fairly easy: https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3.
