### ISSUE TITLE
Asterisks Break LaTeX

### ISSUE THREAD

**Issue by austinmohr** [jamesdabbs/pi-base#44]
Code such as 

```
Test $x^*$ Test $x^*$
```

does not render properly, probably due to markdown reading this as a request for italics. The command \ast renders a better asterisk anyway, so it should be preferred. I have change to \ast wherever I have encountered *.

**Comment by jamesdabbs** [comment]
Should be fixed in the Haskell version; please open issues there if you encounter any bugs.
