### ISSUE TITLE
Strange Implication Involving T1

### ISSUE THREAD

**Issue by austinmohr** [jamesdabbs/pi-base#45]
http://pi-base.herokuapp.com/traits/2723

Pi-Base has automatically generated that this space is T1 based on an unrelated string of implications. While this is a "generic" topology when the underlying set is not specified, I believe it is true that no Right Order space is T1 since, given any two points, any open set that contains the leftmost point must also contain the rightmost.

I have not seen this strange implication in any other space.

**Comment by jamesdabbs** [comment]
This trait is not present in the new database (re-run deduction on the new engine), so I'm closing this issue. Please file bugs there if you see any other strange implication chains.
